// Code generated by counterfeiter. DO NOT EDIT.
package pkgfakes

import (
	"sync"

	"github.com/vmware-labs/marketplace-cli/v2/pkg"
	"helm.sh/helm/v3/pkg/chart"
)

type FakeChartLoaderFunc struct {
	Stub        func(string) (*chart.Chart, error)
	mutex       sync.RWMutex
	argsForCall []struct {
		arg1 string
	}
	returns struct {
		result1 *chart.Chart
		result2 error
	}
	returnsOnCall map[int]struct {
		result1 *chart.Chart
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeChartLoaderFunc) Spy(arg1 string) (*chart.Chart, error) {
	fake.mutex.Lock()
	ret, specificReturn := fake.returnsOnCall[len(fake.argsForCall)]
	fake.argsForCall = append(fake.argsForCall, struct {
		arg1 string
	}{arg1})
	stub := fake.Stub
	returns := fake.returns
	fake.recordInvocation("ChartLoaderFunc", []interface{}{arg1})
	fake.mutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return returns.result1, returns.result2
}

func (fake *FakeChartLoaderFunc) CallCount() int {
	fake.mutex.RLock()
	defer fake.mutex.RUnlock()
	return len(fake.argsForCall)
}

func (fake *FakeChartLoaderFunc) Calls(stub func(string) (*chart.Chart, error)) {
	fake.mutex.Lock()
	defer fake.mutex.Unlock()
	fake.Stub = stub
}

func (fake *FakeChartLoaderFunc) ArgsForCall(i int) string {
	fake.mutex.RLock()
	defer fake.mutex.RUnlock()
	return fake.argsForCall[i].arg1
}

func (fake *FakeChartLoaderFunc) Returns(result1 *chart.Chart, result2 error) {
	fake.mutex.Lock()
	defer fake.mutex.Unlock()
	fake.Stub = nil
	fake.returns = struct {
		result1 *chart.Chart
		result2 error
	}{result1, result2}
}

func (fake *FakeChartLoaderFunc) ReturnsOnCall(i int, result1 *chart.Chart, result2 error) {
	fake.mutex.Lock()
	defer fake.mutex.Unlock()
	fake.Stub = nil
	if fake.returnsOnCall == nil {
		fake.returnsOnCall = make(map[int]struct {
			result1 *chart.Chart
			result2 error
		})
	}
	fake.returnsOnCall[i] = struct {
		result1 *chart.Chart
		result2 error
	}{result1, result2}
}

func (fake *FakeChartLoaderFunc) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.mutex.RLock()
	defer fake.mutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeChartLoaderFunc) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ pkg.ChartLoaderFunc = new(FakeChartLoaderFunc).Spy
