# Copyright 2023 VMware, Inc.
# SPDX-License-Identifier: BSD-2-Clause

---
platform: linux

params:
  CSP_API_TOKEN: ((marketplace_api_token))
  MARKETPLACE_ENV:
  ASSET_TYPE:
  PRODUCT_SLUG:
  PRODUCT_VERSION:
  MKPCLI_DEBUG: true
  MKPCLI_DEBUG_REQUEST_PAYLOADS: true

inputs:
  - name: source

run:
  path: source/ci/tasks/download-asset.sh
