// Code generated by counterfeiter. DO NOT EDIT.
package cspfakes

import (
	"sync"

	"github.com/golang-jwt/jwt"
	"github.com/vmware-labs/marketplace-cli/v2/internal/csp"
)

type FakeTokenParserFn struct {
	Stub        func(string, jwt.Claims, jwt.Keyfunc) (*jwt.Token, error)
	mutex       sync.RWMutex
	argsForCall []struct {
		arg1 string
		arg2 jwt.Claims
		arg3 jwt.Keyfunc
	}
	returns struct {
		result1 *jwt.Token
		result2 error
	}
	returnsOnCall map[int]struct {
		result1 *jwt.Token
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeTokenParserFn) Spy(arg1 string, arg2 jwt.Claims, arg3 jwt.Keyfunc) (*jwt.Token, error) {
	fake.mutex.Lock()
	ret, specificReturn := fake.returnsOnCall[len(fake.argsForCall)]
	fake.argsForCall = append(fake.argsForCall, struct {
		arg1 string
		arg2 jwt.Claims
		arg3 jwt.Keyfunc
	}{arg1, arg2, arg3})
	stub := fake.Stub
	returns := fake.returns
	fake.recordInvocation("TokenParserFn", []interface{}{arg1, arg2, arg3})
	fake.mutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return returns.result1, returns.result2
}

func (fake *FakeTokenParserFn) CallCount() int {
	fake.mutex.RLock()
	defer fake.mutex.RUnlock()
	return len(fake.argsForCall)
}

func (fake *FakeTokenParserFn) Calls(stub func(string, jwt.Claims, jwt.Keyfunc) (*jwt.Token, error)) {
	fake.mutex.Lock()
	defer fake.mutex.Unlock()
	fake.Stub = stub
}

func (fake *FakeTokenParserFn) ArgsForCall(i int) (string, jwt.Claims, jwt.Keyfunc) {
	fake.mutex.RLock()
	defer fake.mutex.RUnlock()
	return fake.argsForCall[i].arg1, fake.argsForCall[i].arg2, fake.argsForCall[i].arg3
}

func (fake *FakeTokenParserFn) Returns(result1 *jwt.Token, result2 error) {
	fake.mutex.Lock()
	defer fake.mutex.Unlock()
	fake.Stub = nil
	fake.returns = struct {
		result1 *jwt.Token
		result2 error
	}{result1, result2}
}

func (fake *FakeTokenParserFn) ReturnsOnCall(i int, result1 *jwt.Token, result2 error) {
	fake.mutex.Lock()
	defer fake.mutex.Unlock()
	fake.Stub = nil
	if fake.returnsOnCall == nil {
		fake.returnsOnCall = make(map[int]struct {
			result1 *jwt.Token
			result2 error
		})
	}
	fake.returnsOnCall[i] = struct {
		result1 *jwt.Token
		result2 error
	}{result1, result2}
}

func (fake *FakeTokenParserFn) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.mutex.RLock()
	defer fake.mutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeTokenParserFn) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ csp.TokenParserFn = new(FakeTokenParserFn).Spy
